import facts from './app-facts.json';
export { facts };
export const courseNotes: Record<string, { native: string; note: string }> = {
  en: { native: 'Hello', note: 'American or British English, everyday speaking and tricky sounds.' },
  zh: { native: '你好', note: 'Characters, pinyin and Mandarin tone practice.' },
  yue: { native: '你好呀', note: 'Traditional characters, Jyutping and six-tone practice.' },
  ja: { native: 'こんにちは', note: 'Everyday Japanese, pronunciation and conversation practice.' },
  ko: { native: '안녕하세요', note: 'Korean sounds, useful phrases and guided conversations.' },
  fr: { native: 'Bonjour', note: 'French pronunciation, everyday situations and sound ladders.' },
  es: { native: 'Hola', note: 'Spanish sounds, useful vocabulary and speaking practice.' },
};
export const screens = [
  { id: 'learn', title: 'Your next small step', label: 'Learn', alt: 'Wunder Tutor Learn screen with Hello and introductions, a daily pronunciation focus and weekly practice challenge.', text: 'Pick up your course, revisit a tricky sound and work towards your daily goal.' },
  { id: 'english-lesson', title: 'Listen. Then say it.', label: 'Speaking lesson', alt: 'English speaking lesson showing the word friend, Listen and Slow buttons, and a microphone button.', text: 'Hear the model at normal or slow speed, then tap the mic to practise.' },
  { id: 'lab', title: 'Give a sound some time', label: 'Pronunciation Lab', alt: 'Pronunciation Lab showing conversation practice and a list of English sounds to work on.', text: 'Practise a sound through syllables, words, phrases and a full sentence.' },
  { id: 'conversations', title: 'Put words into a situation', label: 'Conversations', alt: 'English conversation practice screen with everyday role-play scenarios.', text: 'Choose a guided scenario, speak your replies and review pronunciation feedback.' },
  { id: 'cantonese-lesson', title: 'Make space for Cantonese', label: 'Cantonese lesson', alt: 'Cantonese speaking lesson with Traditional Chinese characters, Jyutping and listening controls.', text: 'Follow Cantonese characters and Jyutping as you practise useful spoken phrases.' },
  { id: 'cantonese-tones', title: 'See the shape of a tone', label: 'Cantonese tone lab', alt: 'Six Cantonese tone contours for si1 to si6 above a pronunciation practice ladder.', text: 'Compare six Cantonese tone contours and work through a dedicated sound ladder.' },
  { id: 'notebook', title: 'Bring your own words', label: 'Notebook', alt: 'Notebook screen with two original English sample sentences and a Start reading button.', text: 'Read a photo or type text, then practise sentence by sentence. English and Mandarin are supported; this example uses typed English.' },
  { id: 'reminders', title: 'Build a gentle routine', label: 'Reminders & rewards', alt: 'Reminders and rewards screen showing a three-day weekly challenge and a daily practice suggestion.', text: 'Choose a schedule, set quiet hours and pause reminders whenever you need to.' },
];
export const FAQ = [
  { q: 'What is Wunder Tutor?', a: 'Wunder Tutor is a pronunciation practice app for children, teens and adults. It combines speaking lessons, listening and reading activities, guided conversations, a Pronunciation Lab and review. Tutu is the in-app learning companion.' },
  { q: 'Which languages can I learn?', a: 'You can learn ' + facts.courses.map(c => c.name).join(', ') + '. There are currently ' + facts.totalLessons + ' course lessons across these seven courses. Course sizes differ; the course cards above show the current counts. Seasonal bonus lessons are separate.' },
  { q: 'What ages is it for?', a: 'The app has four age groups: Little (5–7), Junior (8–11), Teen (12–17) and Adult (18+). Lesson wording, practice situations and presentation adapt to the selected group. A parent or guardian should help a child with setup and microphone consent.' },
  { q: 'Which languages can the app instructions use?', a: 'The interface supports English, Traditional Chinese, Simplified Chinese, Japanese, Korean, French and Spanish. App language is separate from the language you are learning. Some translations are machine drafts and are still awaiting native-speaker review.' },
  { q: 'How does pronunciation feedback work?', a: 'With scoring access, a short recording is sent to Microsoft Azure Speech for assessment. The app uses the result to show scores, highlight words or sounds to practise and offer a retry. Feedback varies by language and exercise. Automatic scores are learning guidance and can be affected by the microphone, background noise and the service’s interpretation.' },
  { q: 'Do I need an invite code? Is the beta free?', a: 'Wunder Tutor is in beta. Full speaking practice, cloud teacher voices and photo reading use authorized access through a valid invite code or an account with access. Open the app to see the available preview and access options. Any result labelled simulated is not an assessment of your voice. A subscription price is not published on this website.' },
  { q: 'Can I choose American or British English?', a: 'Yes. English learners can choose an American or British accent in setup and settings. This controls the requested English speech locale. Other courses use their own language settings.' },
  { q: 'Does Cantonese include Jyutping and tone practice?', a: 'Yes. The Cantonese course has ' + facts.courses.find(c => c.id === 'yue')!.lessons + ' lessons, Traditional Chinese characters, Jyutping, guided conversations and a six-tone chart in the Pronunciation Lab. Cantonese is a separate course from Putonghua.' },
  { q: 'What can I scan or add to Notebook?', a: 'You can photograph or upload a page of English or Chinese text, or type text instead, and practise supported sentences aloud. Chinese reading practice is in Mandarin with pinyin. Scan does not currently provide Cantonese, Japanese, Korean, French or Spanish reading practice. Photo reading needs internet access and authorized service access.' },
  { q: 'Can I choose the teacher voice?', a: 'Yes. Settings lets you choose a primary and backup voice for each course, preview them and reset to app defaults. Mandarin and Cantonese default to Qwen with Google Chirp as backup. The other courses default to Google Chirp with Azure Neural as backup. Availability depends on access and service connection; device speech depends on voices installed on your device.' },
  { q: 'Is progress saved across devices?', a: 'Progress is saved in the browser on the device you use. Signing in to a Wunder Tutor account can sync learner settings, progress, scores and saved page text. Replay recordings and photos are not included in account sync. Without an account, clearing browser data can remove local progress.' },
  { q: 'What happens to voice recordings and photos?', a: 'Voice clips go to Microsoft Azure for scoring. Replay recordings can be kept on your device. If Help improve Wunder Tutor is enabled, the team also keeps practice recordings without a name for up to 90 days. This setting starts enabled for new setups and can be switched off. Photos for reading go to Google Gemini. See the privacy notice for account storage, teacher voices, reminders and deletion controls.' },
  { q: 'Can I practise on a phone, tablet or computer?', a: 'Yes. Open the web app in a modern browser on a device with a microphone. You can add it to your home screen where supported. Cloud scoring, cloud voices, photo reading and account sync need an internet connection. Saved local progress does not replace the connection needed for these services.' },
  { q: 'Are reminders optional?', a: 'Yes. Push reminders start off. Enable them in Reminders & rewards, choose days and time, set quiet hours, or pause and turn them off. Browser and device support varies. The app also has a three-day weekly practice challenge, XP and badges.' },
];
