import { createStore, get, set } from 'idb-keyval';
import type { Accent, Locale, SpeakItem } from '../domain/types';
import { apiFetch, apiHealth } from './health';

/** Mandarin items always speak Mandarin; everything else is English in the child's accent. */
export const localeOf = (item: Pick<SpeakItem, 'lang'> | undefined | null, accent: Accent): Locale => item?.lang ?? accent;

export interface SpeakOptions {
  /** The language to speak in: the child's English accent, or 'zh-CN' for Mandarin. */
  accent: Locale;
  slow?: boolean;
  /** Isolated syllables ("rah", "thee") need different handling from words and sentences. */
  kind?: SpeakItem['kind'];
}

/** Reference ("teacher") audio. Implementations: Gemini Live native audio, device speech synthesis. */
export interface ReferenceVoice {
  available(): boolean;
  speak(text: string, opts: SpeakOptions): Promise<void>;
  stop(): void;
}

// ---------------------------------------------------------------- device speech synthesis (fallback)

// Prefer natural-sounding voices when the platform offers several for the accent.
const PREFERRED = [/natural/i, /neural/i, /google/i, /samantha|daniel|karen|serena/i, /microsoft (aria|jenny|libby|sonia)/i];

class WebSpeechVoice implements ReferenceVoice {
  private voices: SpeechSynthesisVoice[] = [];

  constructor() {
    if (!this.available()) return;
    const load = () => { this.voices = speechSynthesis.getVoices(); };
    load();
    speechSynthesis.addEventListener?.('voiceschanged', load);
  }

  available(): boolean {
    return typeof window !== 'undefined' && 'speechSynthesis' in window && typeof SpeechSynthesisUtterance !== 'undefined';
  }

  private pick(accent: Locale): SpeechSynthesisVoice | undefined {
    const norm = (l: string) => l.replace('_', '-').toLowerCase();
    const exact = this.voices.filter((v) => norm(v.lang) === accent.toLowerCase());
    // Mandarin must never fall back to a Cantonese (zh-HK) or Taiwanese voice, nor to English.
    const pool = exact.length ? exact : accent === 'zh-CN' ? this.voices.filter((v) => /^(zh-cn|cmn)/.test(norm(v.lang))) : this.voices.filter((v) => norm(v.lang).startsWith('en'));
    for (const re of PREFERRED) { const v = pool.find((x) => re.test(x.name)); if (v) return v; }
    return pool[0];
  }

  speak(text: string, { accent, slow }: SpeakOptions): Promise<void> {
    return new Promise((resolve, reject) => {
      if (!this.available()) return reject(new Error('playback-unavailable'));
      speechSynthesis.cancel();
      const u = new SpeechSynthesisUtterance(text);
      const voice = this.pick(accent);
      if (voice) u.voice = voice;
      u.lang = voice?.lang ?? accent;
      u.rate = slow ? 0.55 : 0.92;
      u.pitch = 1.05;
      // Some engines never fire onend (or fire nothing at all when no voice is installed):
      // resolve on a generous timer so the UI can never get stuck in a "playing" state.
      const guard = window.setTimeout(done, 1500 + text.length * (slow ? 190 : 110));
      function done() { clearTimeout(guard); resolve(); }
      u.onend = done;
      u.onerror = (e) => { clearTimeout(guard); e.error === 'interrupted' || e.error === 'canceled' ? resolve() : reject(new Error('playback-unavailable')); };
      speechSynthesis.speak(u);
    });
  }

  stop(): void {
    if (this.available()) speechSynthesis.cancel();
  }
}

// ---------------------------------------------------------------- shared <audio> playback

let current: HTMLAudioElement | null = null;

const pauseCurrent = () => { if (current) { current.pause(); current = null; } };

/** Play a blob (a learner's own take, or a generated teacher take). Resolves when playback ends or is stopped. */
export const playBlob = (blob: Blob): Promise<void> =>
  new Promise((resolve, reject) => {
    pauseCurrent();
    const url = URL.createObjectURL(blob);
    const audio = new Audio(url);
    current = audio;
    const end = () => { URL.revokeObjectURL(url); if (current === audio) current = null; };
    audio.onended = () => { end(); resolve(); };
    audio.onpause = () => { end(); resolve(); };
    audio.onerror = () => { end(); reject(new Error('playback-unavailable')); };
    audio.play().catch((e) => { end(); reject(e); });
  });

// ---------------------------------------------------------------- Gemini Live native audio (via /api/tts)

const ttsKey = (version: string, text: string, o: SpeakOptions) => `${version}|${o.accent}|${o.slow ? 'slow' : 'normal'}|${o.kind === 'syllable' ? 'syl' : ''}|${text}`;

/**
 * Teacher takes generated by the server proxy (Gemini Live). Every take is kept on the device, so
 * a phrase is fetched once and then plays instantly — and keeps working offline.
 */
class GeminiTakes {
  private store = typeof indexedDB !== 'undefined' ? createStore('wunder-tutor-tts', 'takes') : undefined;
  private memory = new Map<string, Blob>();
  private inflight = new Map<string, Promise<Blob>>();
  /** Model/voice the server generates with — a different voice is a different take. */
  version = '';

  fetch(text: string, opts: SpeakOptions): Promise<Blob> {
    const key = ttsKey(this.version, text, opts);
    const hit = this.memory.get(key);
    if (hit) return Promise.resolve(hit);
    let job = this.inflight.get(key);
    if (!job) {
      job = this.load(key, text, opts).finally(() => this.inflight.delete(key));
      this.inflight.set(key, job);
    }
    return job;
  }

  private async load(key: string, text: string, opts: SpeakOptions): Promise<Blob> {
    try {
      const stored = this.store && (await get<Blob>(key, this.store));
      if (stored) { this.memory.set(key, stored); return stored; }
    } catch { /* storage unavailable — fetch instead */ }

    const ctl = new AbortController();
    const timer = setTimeout(() => ctl.abort(), 30000);
    try {
      const res = await apiFetch('/api/tts', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, signal: ctl.signal,
        body: JSON.stringify({ text, accent: opts.accent, slow: !!opts.slow, kind: opts.kind === 'syllable' ? 'syllable' : undefined }),
      });
      if (!res.ok || !res.headers.get('content-type')?.startsWith('audio/')) throw new Error(`tts ${res.status}`);
      const blob = await res.blob();
      this.memory.set(key, blob);
      try { if (this.store) await set(key, blob, this.store); } catch { /* memory cache only */ }
      return blob;
    } finally {
      clearTimeout(timer);
    }
  }
}

// ---------------------------------------------------------------- the voice the app uses

class TeacherVoice implements ReferenceVoice {
  private web = new WebSpeechVoice();
  private takes = new GeminiTakes();
  private gemini: boolean | null = null;
  private ready = apiHealth().then((h) => { this.gemini = h.gemini; this.takes.version = h.ttsVersion; });
  /** Bumped by stop() and by every new speak(), so a slow download can't start talking over something newer. */
  private seq = 0;

  available(): boolean {
    return this.web.available() || this.gemini === true;
  }

  /** Which engine is in use — shown in the Parent Zone. */
  async engine(): Promise<'gemini' | 'device' | 'none'> {
    await this.ready;
    return this.gemini ? 'gemini' : this.web.available() ? 'device' : 'none';
  }

  /** Warm the cache for something the learner is about to hear. */
  prefetch(text: string, opts: SpeakOptions): void {
    void this.ready.then(() => { if (this.gemini) void this.takes.fetch(text, opts).catch(() => undefined); });
  }

  async speak(text: string, opts: SpeakOptions): Promise<void> {
    const mine = ++this.seq;
    this.web.stop();
    pauseCurrent();
    await this.ready;
    if (mine !== this.seq) return;
    if (this.gemini) {
      try {
        const blob = await this.takes.fetch(text, opts);
        if (mine !== this.seq) return;
        return await playBlob(blob);
      } catch {
        if (mine !== this.seq) return;
        // Generation failed or was rejected as inexact — the device voice is better than silence.
      }
    }
    return this.web.speak(text, opts);
  }

  stop(): void {
    this.seq += 1;
    this.web.stop();
    pauseCurrent();
  }
}

export const voice = new TeacherVoice();

export const stopPlayback = (): void => voice.stop();
