export const guidance = {
 greetings: {tip:['Use 唔該 for help or service and 多謝 for a gift. Ask a name with 咩名.','得到幫忙或服務用「唔該」，收到禮物用「多謝」；問名字用「咩名」。','手伝いやサービスには唔該、贈り物には多謝。名前は咩名で尋ねます。','도움이나 서비스에는 唔該, 선물에는 多謝를 씁니다. 이름은 咩名으로 물어요.','Dites 唔該 pour une aide ou un service et 多謝 pour un cadeau. 咩名 demande le nom.','Usa 唔該 por ayuda o servicio y 多謝 por un regalo. 咩名 pregunta el nombre.'],chunks:{4:['我','叫','小明。'],5:['我','學緊','廣東話。']}},
 numbers: {tip:['Use 兩 before the classifier 張 for two tickets. 幾點 asks the time.','兩張票用「兩張飛」；「幾點」用來問時間。','切符二枚は兩張飛。幾點で時刻を尋ねます。','표 두 장은 兩張飛라고 합니다. 幾點으로 시간을 물어요.','Deux billets se dit 兩張飛, avec 兩 devant 張. 幾點 demande l’heure.','Dos billetes se dice 兩張飛, con 兩 delante de 張. 幾點 pregunta la hora.'],chunks:{4:['我','要','兩張飛。'],5:['而家','三點。']}},
 food: {tip:['Use 一杯 for a drink and 一個 for a bun. 唔要冰 means no ice.','飲品用「一杯」，麵包用「一個」；「唔要冰」就是不要冰。','飲み物は一杯、パンは一個と数えます。唔要冰は「氷なし」です。','음료는 一杯, 빵은 一個로 셉니다. 唔要冰는 얼음 없이란 뜻입니다.','Une boisson se compte avec 一杯 et un petit pain avec 一個. 唔要冰 signifie sans glaçons.','Usa 一杯 para una bebida y 一個 para un bollo. 唔要冰 significa sin hielo.'],chunks:{4:['唔該，','一杯茶。'],5:['我','要','一個菠蘿包。']}},
 people: {tip:['鍾意 expresses liking. 一齊 invites someone to do something together.','「鍾意」表示喜歡；「一齊」表示一起做。','鍾意は「好き」、一齊は「一緒に」です。','鍾意는 좋아하다, 一齊는 함께라는 뜻입니다.','鍾意 exprime ce qu’on aime ; 一齊 invite à faire quelque chose ensemble.','鍾意 expresa gustos; 一齊 invita a hacer algo juntos.'],chunks:{4:['我','鍾意','踢波。'],5:['一齊','玩啦！']}},
 out: {tip:['Use 喺邊 to ask where. 轉左 means turn left; 落車 means get off.','「喺邊」問位置；「轉左」是向左轉，「落車」是下車。','喺邊で場所を尋ねます。轉左は「左に曲がる」、落車は「降りる」です。','喺邊으로 위치를 물어요. 轉左는 좌회전, 落車는 내리다입니다.','喺邊 demande où se trouve quelque chose. 轉左 veut dire tourner à gauche et 落車 descendre du véhicule.','喺邊 pregunta dónde está algo. 轉左 es girar a la izquierda y 落車 es bajarse.'],chunks:{4:['唔該，','港鐵站','喺邊？'],5:['行前','少少，','轉左。']}},
 shopping: {tip:['幾多錢 asks the price. In everyday Hong Kong speech, 蚊 means dollars.','「幾多錢」問價錢；香港口語常用「蚊」表示元。','幾多錢で値段を尋ねます。香港の会話では蚊はドルの意味です。','幾多錢으로 가격을 물어요. 홍콩 구어에서 蚊은 달러를 뜻합니다.','幾多錢 demande le prix. À Hong Kong, 蚊 désigne couramment les dollars.','幾多錢 pregunta el precio. En el habla de Hong Kong, 蚊 significa dólares.'],chunks:{4:['呢個','幾多錢？'],5:['呢個','十蚊。']}},
 work: {tip:['我哋 means we. Use 可唔可以 to ask for help and 慢啲 to ask for a slower pace.','「我哋」是我們；用「可唔可以」請人幫忙，用「慢啲」請人放慢。','我哋は「私たち」。可唔可以で助けを求め、慢啲でゆっくり話してもらいます。','我哋는 우리입니다. 可唔可以로 도움을 요청하고 慢啲로 천천히 해 달라고 말해요.','我哋 signifie nous. 可唔可以 demande de l’aide et 慢啲 un rythme plus lent.','我哋 significa nosotros. 可唔可以 pide ayuda y 慢啲 pide ir más despacio.'],chunks:{4:['我哋','一齊','做。'],5:['唔該，','可唔可以','講慢啲？']}}
};
export const order = ['greetings','numbers','family','home','school','animals','weather','feelings','routines','hobbies','food','people','out','shopping','dining','services','health','travel','digital','plans','stories','opinions','work','problems'];
