export const phonetics = [
 {id:'yue:vowels',label:'aa · a',example:'三 saam1',category:'vowel',names:['Long aa and short a','長 aa 與短 a','長いaaと短いa','긴 aa와 짧은 a','aa long et a bref','aa larga y a corta'],tips:['Compare saam1 and sam1. Keep the final m and tone steady while changing the vowel.','比較 saam1 和 sam1。保持 m 韻尾及聲調，只改變元音。','saam1とsam1を比べ、語末のmと声調を保って母音を変えましょう。','saam1과 sam1을 비교하세요. 끝의 m과 성조는 유지하고 모음을 바꾸세요.','Comparez saam1 et sam1 en gardant le m final et le ton, tout en changeant la voyelle.','Compara saam1 y sam1: mantén la m final y el tono mientras cambias la vocal.'],pose:{open:.6,round:0,spread:0,tongue:'low',air:'none',voiced:true},ladders:{syllables:['yue-three','yue-heart'],words:['yue-three','yue-heart'],phrases:['yue-feelings-5'],sentence:['yue-plans-10']}},
 {id:'yue:aspiration',label:'d · t',example:'低 dai1',category:'consonant',names:['A gentle start and a puff of air','不送氣與送氣','息を抑える音と息を出す音','공기를 적게 내는 소리와 내뿜는 소리','Départ doux et souffle d’air','Inicio suave y soplo de aire'],tips:['Compare dai1 and tai1. The t starts with a stronger puff of air; keep the vowel and tone the same.','比較 dai1 和 tai1。t 開頭的氣流較強，元音與聲調保持相同。','dai1とtai1を比べましょう。tは息を強く出し、母音と声調は同じにします。','dai1과 tai1을 비교하세요. t에서 공기를 더 세게 내보내고 모음과 성조는 같게 유지하세요.','Comparez dai1 et tai1 : le t commence par un souffle plus fort, avec la même voyelle et le même ton.','Compara dai1 y tai1: la t empieza con un soplo más fuerte; mantén la vocal y el tono.'],pose:{open:.2,round:0,spread:0,tongue:'ridge',air:'puff',voiced:false},ladders:{syllables:['yue-low','yue-stairs'],words:['yue-low','yue-stairs'],phrases:['yue-weather-6'],sentence:['yue-routines-5']}},
 {id:'yue:rounding',label:'i · yu',example:'書 syu1',category:'vowel',names:['Rounded yu','圓唇 yu','唇を丸めるyu','입술을 둥글게 하는 yu','Le yu arrondi','La yu redondeada'],tips:['Compare si1 and syu1. Start with i, then round your lips while keeping your tongue near the front.','比較 si1 和 syu1。先發 i，再把嘴唇收圓，舌頭仍靠前。','si1とsyu1を比べ、iの舌の位置を前に保ったまま唇を丸めましょう。','si1과 syu1을 비교하세요. i에서 혀를 앞쪽에 둔 채 입술을 둥글게 만드세요.','Comparez si1 et syu1. Partez de i et arrondissez les lèvres en gardant la langue vers l’avant.','Compara si1 y syu1. Parte de i y redondea los labios manteniendo la lengua hacia delante.'],pose:{open:.2,round:.8,spread:0,tongue:'high-front',air:'none',voiced:true},ladders:{syllables:['yue-tone1','yue-book'],words:['yue-tone1','yue-book'],phrases:['yue-services-5'],sentence:['yue-opinions-5']}}
];
export const phoneticItems=[
 ['three','三','saam1',['three','三','三','셋','trois','tres']],
 ['heart','心','sam1',['heart','心','心','마음','cœur','corazón']],
 ['low','低','dai1',['low','低','低い','낮다','bas','bajo']],
 ['stairs','梯','tai1',['ladder','梯子','はしご','사다리','échelle','escalera']],
 ['book','書','syu1',['book','書','本','책','livre','libro']]
];
